exports.seed = function(knex, Promise) {
  return knex('users').del()
  .then(()=>{
    return Promise.all([
      knex('users').insert({
        firstname:'Bob',
        lastname:'Belcher'
      }),
      knex('users').insert({
        firstname:'Linda',
        lastname:'Belcher'
      }),
      knex('users').insert({
        firstname:'Tina',
        lastname:'Belcher'
      }),
      knex('users').insert({
        firstname:'Gene',
        lastname:'Belcher'
      }),
      knex('users').insert({
        firstname:'Louise',
        lastname:'Belcher'
      }),
      knex('users').insert({
        firstname:'Homer',
        lastname:'Simpson'
      }),
      knex('users').insert({
        firstname:'Marge',
        lastname:'Simpson'
      }),
      knex('users').insert({
        firstname:'Bart',
        lastname:'Simpson'
      }),
      knex('users').insert({
        firstname:'Lisa',
        lastname:'Simpson'
      }),
      knex('users').insert({
        firstname:'Maggie',
        lastname:'Simpson'
      }),
      knex('users').insert({
        firstname:'Hank',
        lastname:'Hill'
      }),
      knex('users').insert({
        firstname:'Peggy',
        lastname:'Hill'
      }),
      knex('users').insert({
        firstname:'Bobby',
        lastname:'Hill'
      }),
      knex('users').insert({
        firstname:'Stan',
        lastname:'Marsh'
      }),
      knex('users').insert({
        firstname:'Randy',
        lastname:'Marsh'
      }),
      knex('users').insert({
        firstname:'Eric',
        lastname:'Cartman'
      }),
      knex('users').insert({
        firstname:'Mike',
        lastname:'Ziccardi'
      }),
      knex('users').insert({
        firstname:'Luanne',
        lastname:'Hill'
      }),
      knex('users').insert({
        firstname:'Ladybird',
        lastname:'Hill'
      }),
      knex('users').insert({
        firstname:'Timmy',
        lastname:'Turner'
      }),
      knex('users').insert({
        firstname:'Tommy',
        lastname:'Pickles'
      }),
      knex('users').insert({
        firstname:'Stu',
        lastname:'Pickles'
      }),
      knex('users').insert({
        firstname:'Dill',
        lastname:'Pickles'
      }),
      knex('users').insert({
        firstname:'Hal',
        lastname:'Wilkerson'
      }),
      knex('users').insert({
        firstname:'Louis',
        lastname:'Wilkerson'
      }),
      knex('users').insert({
        firstname:'Francis',
        lastname:'Wilkerson'
      }),
      knex('users').insert({
        firstname:'Reese',
        lastname:'Wilkerson'
      }),
      knex('users').insert({
        firstname:'Malcom',
        lastname:'Wilkerson'
      }),
      knex('users').insert({
        firstname:'Dewey',
        lastname:'Wilkerson'
      }),
      knex('users').insert({
        firstname:'Jamie',
        lastname:'Wilkerson'
      }),

    ])
  })
}
